# version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'python main.py'
    # command: gunicorn -b 0.0.0.0:5000 main:app
    command: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker mainfastapi:app"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://mainuser:root@db/main

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: main
  #     POSTGRES_USER: mainuser
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - .dbdata:/var/lib/postgresql/data
  #   ports:
  #     - 33067:5432

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: mainuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
